name: franch_hub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  pdf: ^3.10.0
  printing: ^5.10.0
  fl_chart:
  carousel_slider:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in: ^6.1.0
  json_annotation:
  bloc:
  flutter_bloc:
  get_it:
  equatable:
  font_awesome_flutter: ^10.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences:
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  build_runner:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  template_arb_file: intl_en.arb
  output_localization_file_name: app_localizations.dart