name: franch_hub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  carousel_slider:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in: ^6.1.0
  json_annotation:
  bloc:
  flutter_bloc:
  get_it:
  equatable:
  font_awesome_flutter: ^10.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences:
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  build_runner:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
