// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-fAAMUnSapXW90xwBw_4x_o9tHAyPS7M',
    appId: '1:812987492440:web:a90d5c5937b265e402822d',
    messagingSenderId: '812987492440',
    projectId: 'franch-hub',
    authDomain: 'franch-hub.firebaseapp.com',
    storageBucket: 'franch-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc9P-lbWoPFUNmUXmhX8fv2BttO7aahRE',
    appId: '1:812987492440:android:6c0cd1e8d5758be302822d',
    messagingSenderId: '812987492440',
    projectId: 'franch-hub',
    storageBucket: 'franch-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM8t3mlt4GkBVV6xzbotR3KLaI50v_YhI',
    appId: '1:812987492440:ios:10e8314dc0fba08702822d',
    messagingSenderId: '812987492440',
    projectId: 'franch-hub',
    storageBucket: 'franch-hub.firebasestorage.app',
    iosBundleId: 'com.example.franchHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM8t3mlt4GkBVV6xzbotR3KLaI50v_YhI',
    appId: '1:812987492440:ios:10e8314dc0fba08702822d',
    messagingSenderId: '812987492440',
    projectId: 'franch-hub',
    storageBucket: 'franch-hub.firebasestorage.app',
    iosBundleId: 'com.example.franchHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-fAAMUnSapXW90xwBw_4x_o9tHAyPS7M',
    appId: '1:812987492440:web:b545089799959e4d02822d',
    messagingSenderId: '812987492440',
    projectId: 'franch-hub',
    authDomain: 'franch-hub.firebaseapp.com',
    storageBucket: 'franch-hub.firebasestorage.app',
  );
}
